### ISSUE TITLE
Access to local files are not supported after upgrading to iOS 16.4

### ISSUE THREAD

**Issue by mhammad-extron** [apache/cordova-plugin-inappbrowser#1003]
# Bug Report

## Problem
Unable to open the local text files after upgrading to iOS 16.4

### What is expected to happen?
Should load and display the text file contents in app browser plugin

### What does actually happen?
I am trying to load a local text file and display its contents using this plugin. 
Since I have upgraded my iPad to iOS 16.4, I have to use 

`<preference name="scheme" value="app" />`

in order to launch the app, otherwise it shows white screen after the splashscreen.

When text file is read, it throws a run time error in XCode i.e. Not Supported.

With 16.2, it was able to load the local files. 

### URL
app://localhost/assets/localfile.txt"
All local files are under the assets folder.

Previously, with 16.2, URL was starting with file://

### ERROR
webView:didFailProvisionalNavigation - -1002: unsupported URL

### Environment, Platform, Device
iOS 16.4 devices

### Version information
I am using Cordova 11.0.0, Cordova iOS 6.3.0
Latest version of cordova-plugin-inappbrowser,
iOS 16.4

## Checklist
- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment]
The InAppBrowser doesn't support schemes (and it never has) and the primarily reason for that is because the InAppBrowser is built to behave as closely to a regular browser so that it can load untrusted third-party content.

As a workaround however I'd try using the [file plugin constants](https://github.com/apache/cordova-plugin-file#ios-file-system-layout) to discover/construct a `file://` path to your local assets. If a `file://` path worked before, it should work if you supply an explicit `file://` path regardless if the cordova webview uses schemes. You'll need to install the `cordova-plugin-file` to use the constants.

`app://localhost/` is generally points to your `www` folder, so assuming that you have `www/assets/localfile.txt` then, an example may look something like:

```js
cordova.InAppBrowser.open(cordova.file.applicationDirectory + "www/assets/localfile.txt", "_blank");
```

**Comment by mhammad-extron** [comment]
> 
Thanks. It worked
