### ISSUE TITLE
Feature - Disable Screenshot

### ISSUE THREAD

**Issue by KerimM** [apache/cordova-plugin-inappbrowser#1006]
# Feature Request
DISABLE SCREENSHOT
## Motivation Behind Feature

Add the option to disable screenshots in the browser to prevent sensitive data from being stolen

## Feature Description

IDK

## Alternatives or Workarounds

There is not

**Comment by breautek** [comment]
It won't be possible via inappbrowser because the standard browser/webview features afaik has no support for disabling screenshots. For this reason I'm closing this issue.

However on the main cordova webview, (which the inappbrowser is a part of) you should be able to install a plugin that exposes an API to disable screenshots while your app is displayed. This plugin is not an endorsement (Never used it or vetted it) but https://github.com/flotrugliocoffice/cordova-plugin-prevent-screenshot-coffice is an example of such plugin.
