### ISSUE TITLE
Cookie deleted after app closes

### ISSUE THREAD

**Issue by samall76** [apache/cordova-plugin-inappbrowser#1010]
# Bug Report
The cookie is deleted when the app closes. 
So I use this method for 4 years and created 40 apps like this. In the beginning some user complained about have to login again. But on my latest app the cookie is deleted (I think) when you completely close the app. 

### Version information

    12.0.0 (cordova-lib@12.0.1) (same problem with version 11.x)
    cordova-ios@7.0.0
    cordova-android@12.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Can you clarify if the issue happens on both android and iOS platform or is this a platform specific issue?

> I use this method for 4 years and created 40 apps like this.

The usage of cookies have undergone a lot of scrutiny over the years and both Google and especially Apple has been implementing changes to guarentee more privacy. Sharing a bit more about how you set your cookies (e.g. what does the `Set-Cookie` header looks like) and whether if you're making cross origin requests might help determine if the issue is actually related to privacy settings.
