### ISSUE TITLE
Unable to get events for _system as target

### ISSUE THREAD

**Issue by supriyamalusare** [apache/cordova-plugin-inappbrowser#1066]
# Bug Report
We are not able to get events in case of target system . We are able to get browser events for target as blank.

## Problem
We are not able to get events in case of target system . We are able to get browser events for target as blank.

### What is expected to happen?
We need to get events for the system target. As we are opening a payment gateway which requires a system browser.
We have to get back to app based on received events.

### What does actually happen?
Currently system browser not sending any events to plugin so unable to get back to app.

### Environment, Platform, Device

Environment - Cordova , platform- android

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
This is intentional and [documented](https://github.com/apache/cordova-plugin-inappbrowser?tab=readme-ov-file#inappbrowseraddeventlistener).

> Adds a listener for an event from the InAppBrowser. (Only available when the target is set to '_blank')

`_system` loads the user's preferred browser app. Despite plugin name, it's not really an  "in-app" browser with this option. Cross communication is limited if not completely restricted thus event propagation cannot be facilitated, because there are no observable events to begin with.

OAuth vendors have started to block webviews because of their nature to modify the loaded content making them untrustful when it comes to authentication. Presumably your payment gateway is requiring the system browser for the same reason. Native approach exposed by a cordova plugin might be necessary to integrate your payment gateway.

[Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs) (not implemented by this plugin) behaves similar to an external "system" browser but is still within the app. I'm not 100% sure on the limitations of Custom Tabs but I believe it will still have a limitation of calling back to your app, so I'm not sure if it will be a sufficient solution. There is a third-party plugin called [cordova-plugin-safariviewcontroller](https://www.npmjs.com/package/cordova-plugin-safariviewcontroller) (Safari View Controller is the iOS equivalent API, but the plugin also implements Android's Custom Tabs). It could be a path worth exploring to confirm one way or another if it's suitable for your situation.
