### ISSUE TITLE
Unable to access facebook page

### ISSUE THREAD

**Issue by BrunoAlan** [apache/cordova-plugin-inappbrowser#1074]
# Bug Report
Unable to access facebook page from inAppBrowser

## Problem
Until September 30 my app could access facebook to log in. 
From today October 1st it is no longer possible using the inAppBrowser, if I use the external browser it works.

### What is expected to happen?
Should be able to access Facebook as you did 1 day ago.

### What does actually happen?

![image](https://github.com/user-attachments/assets/aae55425-c8ed-4f54-9c7b-df1982f44979)

## Information

Does not work on android or ios.
The versions I use are:
“cordova-plugin-inappbrowser": ‘6.0.0’,     
“cordova-ios": ‘7.1.1’,     
“cordova-android": ‘13.0.0’,

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
This doesn't appear to be a bug with in app browser.

The in app browser uses a webview, which is a separate package of the external browser.

Meta could be blocking the webview altogether for security reasons. It is a common tactic for malicious actors to utilise webviews to conduct phishing campaigns since webviews allows the malicious actor to inject scripts into a third-party website and potentially steal user data.

Or the device may have an out-dated webview and the webview version is simply too old and is out of what Facebook supports. In which case the user must log into Google Play (or their app store) and make sure that the system webview is up to date. The current android webview is a min SDK of 26 (Android 8) which means those devices and earlier will not receive webview updates and won't be able to access the latest webview version.

For what it's worth, I've tested using an emulator and in app browser will load up facebook.com (and get redirected to m.facebook.com)

![image](https://github.com/user-attachments/assets/0d3c2cc7-1680-4311-9220-07dd0372f9c9)
