### ISSUE TITLE
Black Screen gets pop up for 2-3 seconds when we open any link using in-app-browser for Android. 

### ISSUE THREAD

**Issue by Akash-Tapadia-DFT** [apache/cordova-plugin-inappbrowser#1075]
# Bug Report

## Problem
We are getting a black screen for around 2 or 3 seconds and then the page starts loading in Android. We are able to reproduce for all Android versions, physical as well as emulators.

Note : For emulators you may get a white screen instead of black.

### What is expected to happen?
Black/White screen should not appear. Flow should be similar to ios.

### What does actually happen?
We get a black/white screen for around 2-3 seconds for Android.

### Command or Code

`inappbrowser.create("<any_url>", '_blank', {})`
e.g url = https://github.com

### Environment, Platform, Device

Platform  : Android

Device : Reproducible on all Android devices

### Version information

Environment Details
ionic        :  6.20.1
cordova   :  10.0.0
node        :  16.14.2
inappbrowser plugin version : 6.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
This sounds more like a slow network/device issue rather than a bug.

The black (or white screen, depending on the configured theme) is generally the about:blank page which is the default page for when there is no page loaded in the webview.

Using `cordova.InAppBrowser.open('https://github.com', '_blank', 'location=yes');` (`inappbrowser.create` is an API that doesn't exist at the cordova plugin level), I see the black screen for approximately 1 second when running on a simulator.

If you want to hide this loading, you can utilise the `hidden` flag so that the IAB isn't immediately visible to the user (but it will still load the page). Then you can utilise the `loadstop` / `loaderror` [listeners](https://github.com/apache/cordova-plugin-inappbrowser?tab=readme-ov-file#inappbrowseraddeventlistener) to show the IAB or display some kind of error feedback.

**Comment by Akash-Tapadia-DFT** [comment]
Thank you for your response @breautek 

I have tried using the flag 'hidden'
And in the loadstop event I am calling the show method for the inappbrowser created before.
Even with this I am getting a glimpse of black screen.
