### ISSUE TITLE
SSL errors handling in Android

### ISSUE THREAD

**Issue by nicolashenry** [apache/cordova-plugin-inappbrowser#292]
Currently when I open a website with InAppBrowser and Android which have an invalid certificate (because of a missing chaining certificate) InAppBrowser only display a black screen and dispatch two event, a "loadstart" event and a "loadend" event.

I think that InAppBrowser should fire a "loaderror" event in order to known that something bad happened with ssl.

**Comment by Vaporexpress** [comment]
Hi.  FYI Google rejected my App until adds this code:
On  "**public class InAppBrowserClient extends WebViewClient**":

```
        // Rejected by Google Play - Failed to validate the certificate chain
        @Override
        public void onReceivedSslError(WebView view, final SslErrorHandler handler, SslError error) {
            final AlertDialog.Builder builder = new AlertDialog.Builder(new ContextThemeWrapper(webView.getContext(), R.style.AlertDialogCustom));
            String message = "SSL Certificate error.";
            switch (error.getPrimaryError()) {
                case SslError.SSL_UNTRUSTED:
                    message = "The certificate authority is not trusted.";
                    break;
                case SslError.SSL_EXPIRED:
                    message = "The certificate has expired.";
                    break;
                case SslError.SSL_IDMISMATCH:
                    message = "The certificate Hostname mismatch.";
                    break;
                case SslError.SSL_NOTYETVALID:
                    message = "The certificate is not yet valid.";
                    break;
            }
            message += " Do you want to continue anyway?";

            builder.setTitle("SSL Certificate Error");
            builder.setMessage(message);
            builder.setPositiveButton("continuar", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                    handler.proceed();
                }
            });
            builder.setNegativeButton("cancelar", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                    handler.cancel();
                    closeDialog();
                }
            });
            final AlertDialog dialog = builder.create();
            dialog.show();
        }
```

**Comment by tonetechnician** [comment]
Hi guys, 

I'm wondering if anyone has had any further experience with this? I have local area network system that intends to use a phone app as a controller. I require access to the phone's gyro and accelerometer so, as far as I can tell, I need to use https to gain access to this.

Since it's a local area server that the phone is interacting with I need to use a self-signed certificate, and am unable to use a CA for two reasons:
1. The app could be used on networks not connected to the internet
2. My server IP can change across networks.

The thing I don't understand is that the app works as it should when I load the apk locally (using debug), but when I upload a release to the app store and download it, it doesn't work, and I'm rather given a popup message "The connection the server was unsuccessful".

Has anyone had any similar experience? Or possibly any sort of work around for it? Would help me so much! So far I've sent a message to Google Play Store and hoping to get a response from them as well. Will post here as well once I have feedback.
