### ISSUE TITLE
Download file not working

### ISSUE THREAD

**Issue by AmedeoLeo** [apache/cordova-plugin-inappbrowser#311]
I am using the inappbrowser to download an .apk file, but the download does not start. 
I've tested the HTML page by using several mobile browser and everything works.
Any feedbacks?

**Comment by klochko7** [comment]
I have the same issue. When I am trying to download apk file from chrome, download does not start.

**Comment by janpio** [comment]
Please create a new Cordova project with a minimal setup to replicate the issue. Then put it on Github and post the link to it here. Thanks.

**Comment by opare** [comment]
I have the same issue too.  Any news about that? Thanks.

**Comment by Macfa** [comment]
same issue here !

**Comment by lovepanda603** [comment]
same issue , Hope to be solved

**Comment by AiNings** [comment]
IOS cannot download online files, have you solved it?

**Comment by JensUweB** [comment]
@janpio How is it going with this? I'm currently facing the same problem. I could setup a minimal repo, if still needed.
This project is still maintained, right?

**Comment by JensUweB** [comment]
I found out whats going on here. InAppBrowser uses the android web view by default. Android Web View does not handle downloads by default, because it cannot render or download files (except html, css & js of course), so you have to register a download listener and handle it yourself. If you don't handle it yourself and just register the listener, the web view will crash (and so will your app), if the user klicks a download link.

As workaround, you can try to modify the java code of the InAppBrowser yourself [as described here](https://stackoverflow.com/questions/30390826/download-file-from-external-website-with-inappbrowser-cordova).
