### ISSUE TITLE
Going back to Cordova from native iOS view

### ISSUE THREAD

**Issue by OmgKevin** [apache/cordova-plugin-inappbrowser#351]
I would like to use this iOS native interface with UINavigationController to return to the JS interface.

**Comment by janpio** [comment]
> this iOS native interface
?

**Comment by OmgKevin** [comment]
I mean, I wrote a plugin, using cordova to push from the html interface to the ios native interface, and then there is a UINavigation on the ios interface, I want to click leftnavbar to return to the html interface, what should I do with your code?

**Comment by janpio** [comment]
Ok. What is the connection to `cordova-plugin-inappbrowser` though?

**Comment by OmgKevin** [comment]
I am confused from the ios native interface dismiss to the html interface. Can I do this with the help of cordova-plugin-inappbrowser?

**Comment by janpio** [comment]
You opened an issue at `cordova-plugin-inappbrowser`, which is a plugin to open a browser/webview inside a Cordova app. Are you trying to reuse some of its code in your custom plugin? I am really confused.

**Comment by OmgKevin** [comment]
> You opened an issue at `cordova-plugin-inappbrowser`, which is a plugin to open a browser/webview inside a Cordova app. Are you trying to reuse some of its code in your custom plugin? I am really confused.

I can't use this plugin to complete that function....？

**Comment by dpa99c** [comment]
> I mean, I wrote a plugin, using cordova to push from the html interface to the ios native interface, and then there is a UINavigation on the ios interface, I want to click leftnavbar to return to the html interface, what should I do with your code?

@OmgKevin from this, I understand:
- you created a plugin which switches from displaying the Cordova Webview (which is displayed by default in Cordova iOS apps and used to render the HTML/JS/CSS components of a Cordova app) to displaying some other native iOS UI. 
- you want to then switch back from displaying the native iOS UI to displaying the Cordova Webview.

Is this correct?

If so, then I'm not sure I understand the relevance of this plugin (cordova-plugin-inappbrowser) to you.
Just to clarify, this plugin enables the opening of an additional native Webview instance in order to display non-Cordova app content (such as an external webpage). This enables the main Cordova Webview (which displays the app UI) to be retained and hidden while the inappbrowser Webview is displayed. When the inappbrowser Webview is dismissed, the main Cordova app Webview is restored to the front of the view hierarchy. Therefore, if you want to switch from displaying the native iOS UI to displaying the Cordova main Webview, this plugin is not relevant to you. What you need to do is restore the Cordova main Webview to the front of the view hierarchy.

It would be most helpful if you could give some code examples of exactly what you are trying to achieve; either a link to your plugin repo or post some code extracts here. Without this, I think we are not clear on what you are trying to achieve.

**Comment by OmgKevin** [comment]
> > I mean, I wrote a plugin, using cordova to push from the html interface to the ios native interface, and then there is a UINavigation on the ios interface, I want to click leftnavbar to return to the html interface, what should I do with your code?
> 
> @OmgKevin from this, I understand:
> 
> * you created a plugin which switches from displaying the Cordova Webview (which is displayed by default in Cordova iOS apps and used to render the HTML/JS/CSS components of a Cordova app) to displaying some other native iOS UI.
> * you want to then switch back from displaying the native iOS UI to displaying the Cordova Webview.
> 
> Is this correct?
> 
> If so, then I'm not sure I understand the relevance of this plugin (cordova-plugin-inappbrowser) to you.
> Just to clarify, this plugin enables the opening of an additional native Webview instance in order to display non-Cordova app content (such as an external webpage). This enables the main Cordova Webview (which displays the app UI) to be retained and hidden while the inappbrowser Webview is displayed. When the inappbrowser Webview is dismissed, the main Cordova app Webview is restored to the front of the view hierarchy. Therefore, if you want to switch from displaying the native iOS UI to displaying the Cordova main Webview, this plugin is not relevant to you. What you need to do is restore the Cordova main Webview to the front of the view hierarchy.
> 
> It would be most helpful if you could give some code examples of exactly what you are trying to achieve; either a link to your plugin repo or post some code extracts here. Without this, I think we are not clear on what you are trying to achieve.

Oh, thank you, my problem has been solved, because I created this code "self.viewController.view.window" when I created "UINavigationController *chatNav = [[UINavigationController alloc] initWithRootViewController:vc];" .rootViewController = chatNav;", so it is not possible to return properly when the iOS native interface dismiss, now I deleted the code, now it is OK, although I still don't know how he affects iOS work.
