### ISSUE TITLE
beforeload callback doesnt get called on Android

### ISSUE THREAD

**Issue by danova123** [apache/cordova-plugin-inappbrowser#413]
Hi Team,
 The beforeload event never gets called. Here is the attached snippet
 I don't know where i am doing it wrong. 

`cordova-plugin-inappbrowser 3.1.0-dev "InAppBrowser"`

      var options = "location=no,hidden=yes;beforeload=yes";
      var target = "_blank";
      var url = "https://s.codepen.io/thesourav/debug/pGEQRw/bZrQWNQDKzwk";
     
      inAppBrowserRef = cordova.InAppBrowser.open(url, target, options);

      inAppBrowserRef.addEventListener("beforeload", function(e, cb){
        console.log("BeforeLoad", e);
        cb(e.url);
      });

Ionic:

```
   ionic (Ionic CLI) : 4.7.1 (C:\Users\sd0003\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.18

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : not available

System:

   NodeJS : v10.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by danova123** [comment]
@jcesarmobile This is a plugin issue. Right 😃

**Comment by jcesarmobile** [comment]
I have never tried beforeload, nor implemented it, so not sure

**Comment by dpa99c** [comment]
I reworked the Android implementation under https://github.com/apache/cordova-plugin-inappbrowser/pull/367 and `beforeload` definitely worked on Android when I did it.

But I've just regression tested and the event is not being fired now because the [`shouldOverrideUrlLoading()` method](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/src/android/InAppBrowser.java#L1171) on the WebViewClient is never getting invoked. 

I wonder if an update to the Android Chrome Webview has broken this, since I'm testing exactly the same code that worked before on exactly the same device... Will investigate...

**Comment by dpa99c** [comment]
The [`shouldInterceptRequest()` method](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/src/android/InAppBrowser.java#L1341) is not getting called either 😕

**Comment by dpa99c** [comment]
@keenan35i any chance you could also retest this on Android?

**Comment by keenan35i** [comment]
@dpa99c sure ill test it again, i didnt do to much android testing on it yet though, but the code posted doesnt look right `var options = "location=no,hidden=yes;beforeload=yes";` in ` hidden=yes;` vs `hidden=yes,` not sure if that would cause this but just throwing that out there

**Comment by jcesarmobile** [comment]
Yeah, that’s the problem, good catch

**Comment by dpa99c** [comment]
@keenan35i well spotted; I'll put my anomalous debugging results down to lack of sleep or lack of beer 😀 
but if this issue arises again, I'll investigate as needed.
