### ISSUE TITLE
After forking the inappbroswer is covering status bar in Android.

### ISSUE THREAD

**Issue by Sushil1091Jes** [apache/cordova-plugin-inappbrowser#469]
# Bug Report

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by Sushil1091Jes** [comment]
![image](https://user-images.githubusercontent.com/43230776/56873935-b35efa80-6a68-11e9-81cc-2db189313178.png)

**Comment by bearforeverfriends** [comment]
I got this issue too.
My inappbrowser is opened with full screen and covering the top status bar.

**Comment by mdewyer** [comment]
Same here. On 3.1.0 and using the options:
`location=no,zoom=no,hidden=yes,toolbar=no,hardwareback=no`

App goes fullscreen / immersive and status bar disappears.

**Comment by janpio** [comment]
Is this a new problem of 3.1.0?

**Comment by mdewyer** [comment]
@janpio The status bar was displaying correctly (not being hidden) in 3.0.0 for me, so I would say yes.

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md
(Please create a branch with 3.0.0 as well so we can compare what happens)

**Comment by bearforeverfriends** [comment]
I figured out how to have my status bar back.
I found that I can pull the status bar out from the top of the screen.
And then when I touch the screen again, it will auto hide to the top of the screen.

Is it a new feature of InAppbrowser?

**Comment by zakm** [comment]
Here's how I was able to reproduce it. First create a clean cordova project with plugin version 3.0.0 to demonstrate expected behaviour.

```sh
cordova create status-bar-issue
cd status-bar-issue/

echo "document.addEventListener('deviceready', () => cordova.InAppBrowser.open( 'https://cordova.apache.org/', '_blank' ) );" > www/js/index.js

cordova platform add android
cordova plugin add cordova-plugin-inappbrowser@3.0.0
cordova run android

# works fine, status bar icons appear
```

![Screenshot_20191025-123916](https://user-images.githubusercontent.com/2751287/67589524-97da6100-f726-11e9-98c3-0c6ea22e2cbb.png)


Then update to 3.1.0 to demonstrate the issue

```
cordova plugin rm cordova-plugin-inappbrowser
cordova plugin add cordova-plugin-inappbrowser@3.1.0
cordova run android

# status bar goes blank as soon as inappbrowser is displayed
```

![Screenshot_20191025-124029](https://user-images.githubusercontent.com/2751287/67589532-9a3cbb00-f726-11e9-8079-eacbb66b479f.png)

**Comment by yesenarman** [comment]
It seems that this issue is related to #257.

ec6af56 is the commit that changed this behavior between 3.0.0 and 3.1.0.

Maybe it should be an option like 'statusbar=no' rather than default behavior?

**Comment by beckiechoi** [comment]
Yeah I can confirm that commenting out the line [716](https://github.com/apache/cordova-plugin-inappbrowser/commit/ec6af56fbd0e2d85f932914da576871da507b4c6#diff-6b96481eda04f0b853d9e7b6637d167bR716) brings back the status bar.

But cordova-plugin-statusbar's `overlaysWebView=true` doesn't work with the inappbrowser with that line commented out. It just takes up the space instead of being an overlay on top of the browser. Not sure if this is the issue on the statusbar plugin, since it works well on cordova's default webview.

Would really appreciate any update on this, it'd be great to have these two plugins work nicely with each other.

**Comment by timbru31** [comment]
Solved by https://github.com/apache/cordova-plugin-inappbrowser/pull/634
