### ISSUE TITLE
Inappbrowser window close when the web view refresh automatically

### ISSUE THREAD

**Issue by mv83** [apache/cordova-plugin-inappbrowser#473]
Hi, I have this problem: I'm trying to open a web page with an inappbrowser window. The webpage refresh automatically every 30 seconds. But when the page refresh, the window stops immediately and is closed.

This is the code I'm using:
`window.open(link,'_blank','location=yes,hidenavigationbuttons=yes,hideurlbar=yes,closebuttoncaption=Close,closebuttoncolor=#707070');`  

Thanks

**Comment by janpio** [comment]
The issue templates are there for a reason. By deleting it and not filling it out, you made sure that your issue is missing vital information. I have no idea what operating system you are talking about, what version (OS, Cordova, plugin) etc.

Please open a new issue and fill the issue template to provide the necessary information. Thanks.
