### ISSUE TITLE
No more releases?

### ISSUE THREAD

**Issue by andreszs** [apache/cordova-plugin-inappbrowser#487]
Hi, I wonder why there hasn't been any release in over a year now... the **postMessage** feature cannot be used with version 3.0.0 that was released in Apr 2018. Is the development of this plugin permantently dropped?

**Comment by janpio** [comment]
Because nobody had the free time to invest to review the merged changes, the outstanding Pull Requests and finally do a Pull Request. Unfortunately there is (almost) no financial support for Apache Cordova any more by any company, so all the contributors are working in their free time, unpaid.

You can help by testing the open Pull Requests or answer Issues. When someone from the team finds the time, that will make it much easier and quicker to get progress.
