### ISSUE TITLE
Android InAppBrowser option to not use fullscreen layout

### ISSUE THREAD

**Issue by ekwok1** [apache/cordova-plugin-inappbrowser#526]
# Feature Request

## Motivation Behind Feature
Provide an option to conditionally set FLAG_FULLSCREEN for window flags when creating main dialog.

## Feature Description
On Android, defaulting to FLAG_FULLSCREEN, hides the Android title bar / status bar. It would be nice to have an InAppBrowserOption to set another flag option to show the status bar.
![image (1)](https://user-images.githubusercontent.com/13550253/63446370-130e5680-c408-11e9-97db-ef18d3264ee2.png)

**Comment by akimakitalo** [comment]
It is also worth noting that the title/status bar disappears from view in android even if the "hidden" option is set to "yes".

Because of this, briefly opening a hidden browser in the background can create unpleasant resizing/flashing when the android title/status momentarily goes away and then comes back.

Did not have this issue in 3.0.0 and I suspect the above is the reason. In 3.0.0, opening a hidden browser did not make the android title/status disappear.

**Comment by timbru31** [comment]
Solved by https://github.com/apache/cordova-plugin-inappbrowser/pull/634
