### ISSUE TITLE
Please release new package without UIWebView 

### ISSUE THREAD

**Issue by MedITSolutionsKurman** [apache/cordova-plugin-inappbrowser#643]
Thanks In advance :)

**Comment by jcesarmobile** [comment]
we will

**Comment by GuilleBarrena** [comment]
when? this week?

**Comment by tryhardest** [comment]
Thank you.

**Comment by brodybits** [comment]
I suggest that people follow up with us maintainers via Slack or on the email forum, follow links in the footer of cordova.io or cordova.apache.org. I am extremely reluctant to make this release myself since I have worked very little with this plugin and am in the middle of an urgent work project.

A possible workaround is to use from a commit on the master branch on GitHub, like this for example:

```
cordova plugin add github:apache/cordova-plugin-inappbrowser#e78ffe7f
```

Most maintainers are overworked volunteers, extremely busy with new major release including cordova-ios with UIWebView completely removed for all users.

**Comment by NiklasMerz** [comment]
We don't have a timeline but if need to submit an app update because of the Apple warning you can do that with the latest release version. See https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html
