### ISSUE TITLE
iOS: opening with target="_blank" not working

### ISSUE THREAD

**Issue by KuschL** [apache/cordova-plugin-inappbrowser#675]
# Bug Report

## Problem
Open the InAppBrowser with target "_blank" in an Ionic app on iOS is not working.

I tried the code below in a new Ionic project and can reproduce the issue.

### What is expected to happen?
The InAppBrowser should open in a new view and show the given website.

### What does actually happen?
The InAppBrowser opens in a new view and don't do anything.

## Information

The problem seems to be new, because we could build a working app last week (2020/04/14).

### Command or Code

```typescript

//page.ts
import {Component} from '@angular/core';
import {InAppBrowser} from "@ionic-native/in-app-browser/ngx";

@Component({
    selector: 'app-page',
    templateUrl: './page.html',
    styleUrls: ['./page.scss'],
})
export class Page {
    public folder: string;

    constructor(private iab: InAppBrowser) {}

    openBrowser() {
        const browser = this.iab.create('https://ionicframework.com/docs/components', '_blank')

        browser.on('beforeload').subscribe((e) => {
            console.log('beforeload', e)
        })

        browser.on('loadstart').subscribe((e) => {
            console.log('loadstart', e)
        })

        browser.on('loaderror').subscribe((e) => {
            console.log('loaderror', e)
        })

        browser.on('customscheme').subscribe((e) => {
            console.log('customscheme', e)
        })

        browser.on('loadstop').subscribe((e) => {
            console.log('loadstop', e)
        })

        browser.on('message').subscribe((e) => {
            console.log('message', e)
        })

        browser.on('exit').subscribe((e) => {
            console.log('exit', e)
        })
    }
}

//page.html
<ion-content>
    <ion-button (click)="openBrowser()">Open browser</ion-button>
</ion-content>
```

### Environment, Platform, Device

Tested on any simulator and iPhone with newest iOS Version (13.4.1)

### Version information

Ionic info:
```
Ionic:

   Ionic CLI                     : 6.6.0 (~/.nvm/versions/node/v13.2.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.0, (and 5 other plugins)

Utility:

   cordova-res : 0.12.1
   native-run  : 1.0.0

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v13.2.0 (~/.nvm/versions/node/v13.2.0/bin/node)
   npm        : 6.14.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.4.1 Build version 11E503a
```
package.json:
```js
{
  "name": "browser-test",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/in-app-browser": "^5.24.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "cordova-ios": "5.1.1",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "core-js": "^2.5.4",
    "native-run": "^1.0.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "~8.3.23",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-inappbrowser": {}
    },
    "platforms": [
      "ios"
    ]
  }
}
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by mzl1988** [comment]
me too

**Comment by mzl1988** [comment]
There is no problem with cordova-plugin-ionic-webview 4.1.3

**Comment by guirip** [comment]
Thank you @mzl1988 
Your comment has been very helpful :clap:

**Comment by tavolondono** [comment]
That's right @mzl1988, with that version 4.1.3 works fine

`cordova plugin add cordova-plugin-ionic-webview@4.1.3`

**Comment by ShaneJohnsonCC** [comment]
Hey @mzl1988 , @guirip , or @tavolondono , can one of you help me connect the dots? In app browser was working perfectly fine for me on ios and then I updated to the latest of everything (ionic, angular, cordova, etc as well as forcing WKWebViewOnly because, well you know) and now it just shows a white screen of death with no errors in console. This is the case for simulator, real device and TestFlight download. I'm pulling hairs trying to get it working again. I downloaded cordova-plugin-ionic-webview, but I'm not sure how that is suppose to help fix this. Thank you so much for your help in advance!

PS, I have tried all the other standard solutions of removing the plugin and adding it again as well as removing the ios platform and re-adding it. No luck...

**Comment by guirip** [comment]
@ShaneJohnsonCC 

**Some context about WebKit webview**
WebKit webview in itself is a big subject. In short, Apple deprecated UIWebView during summer 2018. Everybody should use that WK webview, but this webview was far from offering the same level of stability and feature as UI webview (like good support of file:// protocol!), so there has been quite a fuss!
I suggest reading this for more information:
https://cordova.apache.org/news/2018/08/01/future-cordova-ios-webview.html

A lot of work would be needed to have your app working on WK webview. Fortunately the `cordova-plugin-ionic-webview` would make your app use the WK webview AND ship a whole bunch of patches/tools to help managing the caveats of this webview. (For instance, one of these features is serving your webapp with a local server, so protocol http:// is used instead of file://)

So beware if you are switching from UI web view to WK webview, there may be some more work waiting for you.

**Now, what will probably interest you**
The workaround for this specific InAppBrowser issue is not to use the latest version of `cordova-plugin-ionic-webview` but the version before, where everything was working fine.

:arrow_right:  That version is the version **[4.1.3](https://github.com/ionic-team/cordova-plugin-ionic-webview/releases)**

**Comment by jcesarmobile** [comment]
it's a bug on ionic webview plugin https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/551

**Comment by ShaneJohnsonCC** [comment]
Thanks @guirip and @jcesarmobile ! Very helpful
