### ISSUE TITLE
SSL ERROR

### ISSUE THREAD

**Issue by jdpsbh** [apache/cordova-plugin-inappbrowser#786]
Trying to access this page with inappbrowswer: https://cei.b3.com.br/CEI_Responsivo/login.aspx, but AndroidStudio console show this error:

I/X509Util: Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/chromium: [WARNING:aw_contents_client_bridge.cc(170)] Ignoring unexpected ssl error proceed callback

But this website has its certificate ok. If open this url with any browser,  it works.

I'm running inappbrowser 4.0 with Android 5.1.1

Thanks.

**Comment by faugusztin** [comment]
Your server is misconfigured, the server is missing the intermediate certificates. Many browser include common chain certificates, but not everything does.

If you run the ` openssl s_client -showcerts -connect cei.b3.com.br:443` command, you will see you get following errors:
```
depth=0 C = BR, ST = SP, L = SAO PAULO, OU = DI-GSI - Gestao de Seguranca da Informacao, O = "B3 S.A. - BRASIL, BOLSA, BALCAO", CN = cei.b3.com.br
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = BR, ST = SP, L = SAO PAULO, OU = DI-GSI - Gestao de Seguranca da Informacao, O = "B3 S.A. - BRASIL, BOLSA, BALCAO", CN = cei.b3.com.br
verify error:num=21:unable to verify the first certificate
verify return:1
```
Your HTTPS server must also include the intermediate certificates (for "GlobalSign RSA OV SSL CA 2018") in their SSL response.
https://support.globalsign.com/ca-certificates/intermediate-certificates/organizationssl-intermediate-certificates

**Comment by jdpsbh** [comment]
Hi faugusztin, thanks for answer! The problem is, I don't have access to this server. It's a 3rd party website in which we getting stock market data from. Is there any way to fix this without doing what you suggested?

**Comment by jdpsbh** [comment]
Do you know why it works width default Chrome browser on Android device, but doens't with InappBrowswer?

**Comment by breautek** [comment]
> Hi faugusztin, thanks for answer! The problem is, I don't have access to this server. It's a 3rd party website in which we getting stock market data from. Is there any way to fix this without doing what you suggested?

You could maybe proxy the connection so the android app hits your server, which in turn connects/redirects the connection to cei.b3.com on the behalf of the android client.

This should work if your server has those common chain certificates like faugusztin mentioned, but it's possible that it doesn't and it's not available. If it's not available, then there is no **secure** way to fix this, without getting the system administrators of that server involved.

I'll admit the proxy idea is not really ideal... My personal opinion is to find another source for the market share data, or find a way to get in touch with their system adminstrator to see if they can correct their server configuration.

> Do you know why it works width default Chrome browser on Android device, but doens't with InappBrowswer?

Android docs does a good job describing some of the differences: https://developer.android.com/training/articles/security-ssl#MissingCa

The most interesting note:

> What is interesting to note here is that visiting this server in most desktop browsers does not cause an error like a completely unknown CA or self-signed server certificate would cause. This is because most desktop browsers cache trusted intermediate CAs over time. Once a browser has visited and learned about an intermediate CA from one site, it won't need to have the intermediate CA included in the certificate chain the next time.

This means if on the browser, if visited a website that uses the same CA, and sends the complete chain, websites with the same CA that doesn't send the complete chain will still work because the intermediate is cached and reused across multiple websites using the same certificate authority. The android webviews however does not do this.

Since this issue is not related to Cordova, I'll be closing this issue.
