### ISSUE TITLE
External link with target _blank replacing the app  in v`5.0.0`

### ISSUE THREAD

**Issue by nmanikiran** [apache/cordova-plugin-inappbrowser#852]
# Bug Report
External link with target _blank replacing the app
`in-app-browser` version `5.0.0`

## Problem
when launching the links with `in-app-browser` version 5.0.0 the app is getting replaced with the url
its working fine in version `4.0.0` (cookies are not sharing so upgraded to v 5.0.0 and its replacing the app shell)

### What is expected to happen?
`external` link should open in `in-app-browser` window and with version `5.0.0` the cookies also should be shared

### What does actually happen?
the `external link` is replacing the app and there is no way to go back 
and we need to `force kill / re launch` the app 

### Environment, Platform, Device

Android 10
iOS 14

### Version information

Cordova CLI: `10.0.0`
cordova-ios: `6.1.0`
Xcode: `12.0.1`
Operating System: macbook pro

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by JeffBerman** [comment]
@nmanikiran just curious, are you opening the link with `window.open` or `cordova.InAppBrowser.open`? There was a breaking change some time ago that possibly could have been publicized better. In the past, the plugin set `window.open` to `cordova.InAppBrowser.open` but now it doesn't do that, so you need to call `cordova.InAppBrowser.open` to open a link using the plugin. Otherwise, the link will open in the manner that you have described.

**Comment by nmanikiran** [comment]
> @nmanikiran just curious, are you opening the link with `window.open` or `cordova.InAppBrowser.open`? There was a breaking change some time ago that possibly could have been publicized better. In the past, the plugin set `window.open` to `cordova.InAppBrowser.open` but now it doesn't do that, so you need to call `cordova.InAppBrowser.open` to open a link using the plugin. Otherwise, the link will open in the manner that you have described.

@JeffBerman thanks for the reply

I am doing window.open = `cordova.inAppBrowser.open` and calling

`window.open(url, target)` 

You mean this does work with version 5 ?

We need to use `cordova.inAppBrowser.open(url, target)` ?

**Comment by JeffBerman** [comment]
@nmanikiran You're doing it fine, that should work. The only thing I can think of is to verify that nothing is resetting `window.open` back to its original value. Perhaps to be 100% sure you could change your code to issue a call to `cordova.InAppBrowser.open` instead of `window.open`. Also, you typed `inAppBrowser` above but the object name is capitalized: `InAppBrowser`. Good luck!

**Comment by nmanikiran** [comment]
Hey @JeffBerman 

tried using `cordova.InAppBrowser.open` directly instead of  assigning `window.open` but no luck

**Comment by nmanikiran** [comment]
> I'm sorry, I don't know why it isn't working for you. It works fine for me. Have you tried removing and re-adding the plugin just in case something didn't install correctly?
> 
> Maybe you'd like to post some of your actual code and someone else will have an idea.

Thanks @JeffBerman it worked if i use `cordova.InAppBrowser.open`,  but `cookies ` are not getting shared in `ios`
`WKWebView's ` using `InAppBrowser`- 5.0
