### ISSUE TITLE
I am loading a set of local files within inappbrwser but plugins not geting called

### ISSUE THREAD

**Issue by ncomo11** [apache/cordova-plugin-inappbrowser#897]
# Bug Report
Inside inappbrowser other cordova plugins are not getting called.

## Problem
I am loading a set of local files within inappbrwser but plugins not geting called

### What is expected to happen?
Code loaded inside inappbrowser should be able to call cordova plugins

### What does actually happen?
Code inside inappbrowser do call JS code of plugin but gets lost (not able to call plugin native code) after below line:

"nativeApiProvider.get().exec(..." in cordova.js

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
The in-app browser plugin is an isolated webview intended to provide a secure way to view remote content. It's **not suppose** to have access to plugin APIs. Doing so would be a breach in both Apple's App Store and Google's Play Store policies.

I understand this might not apply directly to you, since you said all your files are local but the InApp Browser webview is missing implementations to handle cross environment communication between native land and JS land and that is intentional. For this reason, I'll be closing this issue.

If you need to use cordova plugins, you have to remain in the "Cordova Webview", that is the webview that your main index.html launches in. If you need support, I'd recommend asking our [Slack community](http://slack.cordova.io/).

Kind regards,
Norman

**Comment by ncomo11** [comment]
Hi! 
I do agree to this but yes I missed this part in the documentation.

Thanks,
