### ISSUE TITLE
Remove android.permissions.INTERNET permission

### ISSUE THREAD

**Issue by Mike-the-one** [apache/cordova-plugin-inappbrowser#926]
Thanks for this great plugin, I am using this plugin in my app to launch external URL (using target `_system`), I forced to remove internet access from permission setting and now the bundle detail shows

```sh
android.permission.ACCESS_COARSE_LOCATION, 
android.permission.ACCESS_FINE_LOCATION, 
android.permission.CAMERA, 
android.permission.FLASHLIGHT, 
android.permission.READ_EXTERNAL_STORAGE, 
android.permission.RECEIVE_BOOT_COMPLETED, 
android.permission.VIBRATE, 
android.permission.WAKE_LOCK, 
android.permission.WRITE_EXTERNAL_STORAGE
```

But when on playstore app listing, I still see this:

```sh
prevent device from sleeping
full network access
run at startup
control flashlight
control vibration
view network connections
```

So how can I fix it?

Thanks

**Comment by jcesarmobile** [comment]
This plugin doesn’t add the internet permission, it probably comes from cordova-android directly.
https://github.com/apache/cordova-android/blob/a1ed1c0af7c6267f47e580e8850295202692f4ea/templates/project/AndroidManifest.xml#L31

Since it’s required by cordova itself I don’t think you can remove it.
You can try to use manifest merger to remove permissions.
https://developer.android.com/studio/build/manage-manifests
