### ISSUE TITLE
Slack Warning: This browser won't be supported starting March 1, 2022. Update your browser to keep using Slack

### ISSUE THREAD

**Issue by thambui** [apache/cordova-plugin-inappbrowser#933]
# This browser won't be supported starting March 1, 2022. Update your browser to keep using Slack

I'm using inappbrowser to login with Slack and got the warning. Althought I use the newest version of Plugin (5.0.0), I still got the error. Could someone can help me.

**Comment by NiklasMerz** [comment]
This plugin only uses the webview engine provided by the OS. On a different device or OS you probably won't get this warning. We probably nothing do about that.

**Comment by timbru31** [comment]
I agree with what Niklas said. They could just use User Agent sniffing or identify the browser by features.  
Furthermore, your issue is missing a lot of required information. I'd like you to invite you to our [Slack community](http://slack.cordova.io) to discuss this matter - we use this issue tracker for bugs only and not for user support.
