### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by damianlluch** [apache/cordova-plugin-inappbrowser#991]
Hi, I have a web app working with the inappbrowser plugin on Android. What I need is to add push notifications. I haven't found any guides or examples of how to do it with a project in inappbrowser.
I am using Angular and Capacitor.

Is it possible to add push notifications? any example?

thanks

**Comment by WoAiNii** [comment]
You can give [Firebase](https://capacitorjs.com/docs/guides/push-notifications-firebase) a try, I don't think it's a matter of InAppBrowser.

**Comment by breautek** [comment]
It won't be possible to implement push notifications in an app running inside an InAppBrowser.

The InAppBrowser is intended to be an isolated webview without the native bridge so that it can safely display remote untrusted content. Which means you'll need to rely on pure web technologies to implement Push notifications. A pure web solution to push notifications makes use of Service Workers, which is only implemented in the browser counterpart and is not available in the underlying native webviews that both Cordova and InAppBrowser depends on.

This means you'll have to make use of a cordova plugin that implements a native push notification solution, such as firebase (and the `cordova-plugin-firebase` plugin counterpart). This has to run on the main cordova webview side, not inside the InAppBrowser. It **may** be possible to have events be propagated to the InAppBrowser instance by using [executeScript](https://github.com/apache/cordova-plugin-inappbrowser#inappbrowserexecutescript).

Closing as not-a-bug.
