### ISSUE TITLE
InAppBrowserEvent message - not for ios - update doc required.

### ISSUE THREAD

**Issue by grekpg** [apache/cordova-plugin-inappbrowser#993]
https://ionicframework.com/docs/v3/native/in-app-browser/ 

ref.on('message').subscribe((message) => {  

this not work on IOS - so please change documentation - message in not available i IOS ?

**Comment by breautek** [comment]
Apache Cordova does not maintain the ionic framework or it's website.

If the Ionic Framework is using this plugin internally, our docs states `Only available when the target is set to '_blank'`.

So if you are not using `_blank` target when creating the InAppBrowser, then that could be it isn't working, in which case it's likely intentional.

If you are using `_blank` and is still having problems, then I'd suggest creating a simple sample project that purely uses Cordova without any frameworks and see if the issue still persists. If it does, it can serve as a test app for a bug ticket.
